name = "RescaleTimeSeries"
uuid = "83e3bd76-daf5-40b1-bd70-0477bea61f1c"
authors = ["GKrivtchik <47811556+GKrivtchik@users.noreply.github.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
